name: ${project.artifactId}Bukkit
main: ${project.groupId}.bukkit.${project.artifactId}Bukkit
version: ${project.version} ${myBuildNumberVariable}
author: xXSchrandXx
description: ${project.artifactId}Bukkit
softdepend: []
api-version: 1.13